config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'questions#index'
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :a_answer
  validates_presence_of :b_answer
  validates_presence_of :a_votes
  validates_presence_of :b_votes
  belongs_to :user

  def self.search(search)
    if search
      where("a_answer LIKE :search OR b_answer LIKE :search", search: "%#{search}%")
    else
      where(nil)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  helper ApplicationHelper
  helper_method :sort_column, :sort_direction

  def index
    @questions = Question.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = "Save successful"
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save"
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @questions = Question.all
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Save successful"
      respond_to do |format|
        format.html { redirect_to question_path(@question) }
        format.js
      end
    else
      flash[:alert] = "Failed to save"
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
  end

  private

  def sort_column
    Question.column_names.include?(params[:sort]) ? params[:sort] : "a_votes"
  end

  def sort_direction
    %w[ASC DESC].include?(params[:direction]) ? params[:direction] : "ASC"
  end

  def question_params
    params.require(:question).permit(:a_answer, :b_answer, :a_votes, :b_votes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def vote_percentage(x, y)
    if x == 0
      0
    else
      vote_float = ( x / (x + y) ) *100
      vote_float.round
    end
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == params[:sort] && params[:direction] == "ASC" ?
    "DESC" : "ASC"
    link_to title, url_for(:sort => column, :direction => direction, :page => nil), {:class => css_class, :remote => true}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WouldYouRatherClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-inverse navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Would You Rather", root_path, :class => 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Sort", root_path%></li>
            <li><%= link_to "Categories", root_path%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= form_tag(questions_path, method: "get", class: "navbar-form") do %>
              <div class="form-group">
                <%= text_field_tag(:search, params[:search]) %>
                <%= submit_tag("Search", class: "btn btn-default", :name => nil) %>
              </div>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-user"><%= current_user.email %></li>
              <li><%= link_to "Ask", new_question_path%></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <% if flash[:notice] %>
      <p class="alert alert-success"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <p class="alert alert-danger"><%= flash[:alert] %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :a_answer %>
  <%= f.input :b_answer %>
  <%= f.submit %>
<% end %>

app/views/questions/_question.html.erb
<%= sortable "a_votes", "A Team"%>
<%= sortable "b_votes", "B Team"%>

<% @questions.each do |question| %>
  <div id='<%= question.id %>'>
    <%= render 'question_tile', question: question %>
  </div>
<%end%>

app/views/questions/_question_tile.html.erb
<h1>Would you rather </h1>
<%= question.a_answer %>
Number of a votes: <%= question.a_votes %>
<p id='<%= question.id %>_a'><%= vote_percentage(question.a_votes, question.b_votes) %></p>
<%= form_for question, remote: true do |f| %>
  <%= f.hidden_field :a_votes, :value => question.a_votes + 1 %>
  <%= f.button "Choose"%>
<%end%>
<%= question.b_answer %>
Number of b votes: <%= question.b_votes %>
<p id='<%= question.id %>_b'><%= vote_percentage(question.b_votes, question.a_votes) %></p>
<%= form_for question, remote: true do |f| %>
  <%= f.hidden_field :b_votes, :value => question.b_votes + 1 %>
  <%= f.button "Choose"%>
<%end%>

app/views/questions/edit.html.erb
<%= render 'form' %>

<%= link_to "Back", question_path(@question) %>

app/views/questions/index.html.erb
<%= form_tag questions_path, method: 'get', id: 'questions_search' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<div id="question-list">
  <%= render 'question' %>
</div>

<div id="pagination">
  <%= will_paginate @questions, {link_options: {'data-remote': true}} %>
</div>

app/views/questions/index.js.erb
$("#question-list").html("<%= j render 'question'%>")

app/views/questions/new.html.erb
<%= render 'form' %>

<%= link_to "Back", questions_path %>

app/views/questions/show.html.erb
<h1>Would you rather </h1>
<%= @question.a_answer %>
<%= @question.b_answer %>

app/views/questions/update.js.erb
$('#' + '<%= @question.id %>').html('<%= j render "question_tile", question: @question %>')

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>